import { Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  subsets:['latin'],
  weight:"200" 
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-purple-100`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
