
export const metadata = {
  title: "Admin:Create Next App",
  description: "Admin:Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
<div>Admin Nav bar</div>
    {children}
    </>
);
}
